title: "~"
description: René's Home
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://renegarcia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ixxra
github_username: renegarcia
# Build settings
theme:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
